# -*- coding: utf-8 -*-
"""Copy of PROPERTY.ipynb DATA GROUP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QGf5RM-n0udxTgiVbXasQcmM5Zj8B2y

**PROPERTY MARKET ANALYSIS**

ADVANCED DATA SCIENCE & ANALYTICS GROUP 17

**IMPORTING REQUIRED LIBRARIES**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**IMPORTING DATASET FROM KAGGLE**"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("new-york-city/nyc-property-sales")

print("Path to dataset files:", path)

"""**READING THE DATASET**"""

import os
import pandas as pd

# List files in the downloaded dataset path
files = os.listdir(path)
print(f"Files in the dataset directory: {files}")

# Assuming the main data file is a CSV, let's find and load it
csv_file = [f for f in files if f.endswith('.csv')]

if csv_file:
    # Assuming the first CSV file found is the one to load
    data_file_path = os.path.join(path, csv_file[0])
    df = pd.read_csv(data_file_path)
    print(f"Successfully loaded {len(df)} rows from {csv_file[0]}")
    print(df.head())
else:
    print("No CSV files found in the dataset directory.")

print(f"The dataset has {df.shape[0]} rows and {df.shape[1]} columns.")

df['SALE DATE'] = pd.to_datetime(df['SALE DATE'], errors='coerce')
min_year = df['SALE DATE'].min().year
max_year = df['SALE DATE'].max().year
print(f"The data covers the period from {min_year} to {max_year}.")

"""**DATA CLEANING**"""

print("Original DataFrame shape:", df.shape)

# Convert 'SALE PRICE' to numeric, coerce errors to NaN
df['SALE PRICE'] = pd.to_numeric(df['SALE PRICE'], errors='coerce')

# Filter out sales where sale_price is 0 or less than 10000
df = df[df['SALE PRICE'] >= 10000].copy()
print("Shape after filtering sale price (>= 10000):", df.shape)

# Convert 'GROSS SQUARE FEET' to numeric, coerce errors to NaN
df['GROSS SQUARE FEET'] = pd.to_numeric(df['GROSS SQUARE FEET'], errors='coerce')

# Filter out rows where gross_square_feet is 0 or NaN
df = df[df['GROSS SQUARE FEET'] > 0].copy()
df = df.dropna(subset=['GROSS SQUARE FEET']).copy()
print("Shape after filtering gross square feet (> 0 and not NaN):", df.shape)

# Filter for residential properties: building_class_category LIKE '01%' OR '02%' OR '03%'
residential_categories = df['BUILDING CLASS CATEGORY'].astype(str).str.startswith(('01', '02', '03'))
df = df[residential_categories].copy()
print("Shape after filtering for residential properties:", df.shape)

print("Data cleaning complete. Displaying the first 5 rows of the cleaned data:")
print(df.head())

"""**CALCULATING THE NUMBER OF SALES REMAINING**"""

# Calculate number of sales remaining
num_sales_remaining = df.shape[0]
print(f"Number of sales remaining after filtering: {num_sales_remaining}")

# Convert 'SALE DATE' to datetime objects if not already done
# (Assuming this was already done in a previous cell like IUO7RNZg16_P, but re-confirming for safety)
if not pd.api.types.is_datetime64_any_dtype(df['SALE DATE']):
    df['SALE DATE'] = pd.to_datetime(df['SALE DATE'], errors='coerce')

# Get the minimum and maximum sale dates
min_date = df['SALE DATE'].min().strftime('%Y-%m-%d')
max_date = df['SALE DATE'].max().strftime('%Y-%m-%d')

print(f"Date range covered: {min_date} to {max_date}")

print(f"The dataset after cleaning has {df.shape[0]} rows and {df.shape[1]} columns.")

"""**EXPLORATORY DATA ANALYSIS**

REMAINING SALES & DATE RANGE COVERED
"""

# Calculate number of sales remaining
num_sales_remaining = df.shape[0]
print(f"Number of sales remaining after filtering: {num_sales_remaining}")

# Convert 'SALE DATE' to datetime objects
df['SALE DATE'] = pd.to_datetime(df['SALE DATE'], errors='coerce')

# Get the minimum and maximum sale dates
min_date = df['SALE DATE'].min().strftime('%Y-%m-%d')
max_date = df['SALE DATE'].max().strftime('%Y-%m-%d')

print(f"Date range covered: {min_date} to {max_date}")

df.head(5)

"""**MATCH BOROUGH NAME TO COUNTY NAME**"""

# Mapping Borough numbers to County Names
borough_to_county = {
    1: 'New York County (Manhattan)',
    2: 'Bronx County',
    3: 'Kings County (Brooklyn)',
    4: 'Queens County',
    5: 'Richmond County (Staten Island)'
}

df['COUNTY_NAME'] = df['BOROUGH'].map(borough_to_county)

print("Added 'COUNTY_NAME' column to the DataFrame. First 5 rows:")
print(df[['BOROUGH', 'COUNTY_NAME', 'SALE PRICE']].head())

"""AVERAGE SALES BY BOROUGH"""

avg_price_by_borough = df.groupby('COUNTY_NAME')['SALE PRICE'].mean().sort_values(ascending=False)

print("Average Sale Price by Borough:")
print(avg_price_by_borough)

most_expensive_borough_name = avg_price_by_borough.index[0]
most_expensive_borough_price = avg_price_by_borough.iloc[0]
least_expensive_borough_name = avg_price_by_borough.index[-1]
least_expensive_borough_price = avg_price_by_borough.iloc[-1]

print(f"\nThe most expensive borough is {most_expensive_borough_name} with an average sale price of ${most_expensive_borough_price:,.2f}.")
print(f"The least expensive borough is {least_expensive_borough_name} with an average sale price of ${least_expensive_borough_price:,.2f}.")

"""**THE DISTRIBUTION OF SALES PRICE**"""

plt.figure(figsize=(12, 6))
sns.histplot(df['SALE PRICE'], bins=50, kde=True)
plt.title('Distribution of Sale Price')
plt.xlabel('Sale Price ($)')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)
plt.show()

skewness = df['SALE PRICE'].skew()
mean_price = df['SALE PRICE'].mean()
median_price = df['SALE PRICE'].median()

print(f"\nSkewness of Sale Price: {skewness:.2f}")
print(f"Mean Sale Price: ${mean_price:,.2f}")
print(f"Median Sale Price: ${median_price:,.2f}")

if skewness > 0.5:
    print("The distribution of Sale Price is positively (right) skewed, indicating a longer tail on the right side due to a few very high sale prices.")
elif skewness < -0.5:
    print("The distribution of Sale Price is negatively (left) skewed, indicating a longer tail on the left side due to a few very low sale prices.")
else:
    print("The distribution of Sale Price is relatively symmetrical.")

print(f"A typical sale price, often better represented by the median in skewed distributions, is approximately ${median_price:,.2f}.")

"""**AVERAGE PRICE PER SQUARE FOOT**"""

# Calculate price per square foot
df['PRICE_PER_SQFT'] = df['SALE PRICE'] / df['GROSS SQUARE FEET']

# Calculate average price per square foot by borough
avg_price_sqft_by_borough = df.groupby('COUNTY_NAME')['PRICE_PER_SQFT'].mean().sort_values(ascending=False)

print("Average Price Per Square Foot by Borough:")
print(avg_price_sqft_by_borough)

# Identify the borough with the highest price per square foot
highest_price_sqft_borough = avg_price_sqft_by_borough.index[0]
highest_price_sqft_value = avg_price_sqft_by_borough.iloc[0]

print(f"\nThe borough with the highest average price per square foot is {highest_price_sqft_borough} with an average of ${highest_price_sqft_value:,.2f} per square foot.")

"""**AVERAGE PRICE OVER TIME (YEARS)**"""

df['SALE_YEAR'] = df['SALE DATE'].dt.year

avg_sale_price_by_year = df.groupby('SALE_YEAR')['SALE PRICE'].mean()

plt.figure(figsize=(10, 6))
avg_sale_price_by_year.plot(kind='line', marker='o')
plt.title('Average Sale Price Over Time (by Year)')
plt.xlabel('Year')
plt.ylabel('Average Sale Price ($)')
plt.grid(True)
plt.xticks(avg_sale_price_by_year.index)
plt.tight_layout()
plt.show()

print("Average Sale Price by Year:")
print(avg_sale_price_by_year)

print("Data types for each variable:")
df.info()

df['SALE DATE'] = pd.to_datetime(df['SALE DATE'], errors='coerce').dt.date
print("Updated 'SALE DATE' column to date format.")
print(df['SALE DATE'].head())
print(df['SALE DATE'].dtype)

"""**"""



# Ensure 'SALE DATE' is in datetime format before extracting month and year
df['SALE DATE'] = pd.to_datetime(df['SALE DATE'])

# Extract month and year to create a monthly period
df['SALE_MONTH_YEAR'] = df['SALE DATE'].dt.to_period('M')

# Calculate the average sale price by month
avg_sale_price_by_month = df.groupby('SALE_MONTH_YEAR')['SALE PRICE'].mean()

# Plotting the average sale price over time by month
plt.figure(figsize=(14, 7))
avg_sale_price_by_month.plot(kind='line', marker='o')
plt.title('Average Sale Price Over Time (by Month)')
plt.xlabel('Month-Year')
plt.ylabel('Average Sale Price ($)')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print("Average Sale Price by Month:")
print(avg_sale_price_by_month)

avg_price_by_neighborhood = df.groupby('NEIGHBORHOOD')['SALE PRICE'].mean().sort_values(ascending=False)

print("Neighborhoods with Highest Average Sale Price:")
print(avg_price_by_neighborhood.head())

print("\nNeighborhoods with Lowest Average Sale Price:")
print(avg_price_by_neighborhood.tail())

highest_neighborhood = avg_price_by_neighborhood.index[0]
highest_price = avg_price_by_neighborhood.iloc[0]
lowest_neighborhood = avg_price_by_neighborhood.index[-1]
lowest_price = avg_price_by_neighborhood.iloc[-1]

print(f"\nThe neighborhood with the highest average sale price is {highest_neighborhood} with an average of ${highest_price:,.2f}.")
print(f"The neighborhood with the lowest average sale price is {lowest_neighborhood} with an average of ${lowest_price:,.2f}.")

import matplotlib.pyplot as plt
import seaborn as sns

# Get the top 5 and bottom 5 neighborhoods by average sale price
top_5_neighborhoods = avg_price_by_neighborhood.head(5)
bottom_5_neighborhoods = avg_price_by_neighborhood.tail(5)

# Combine them for plotting
neighborhood_plot_data = pd.concat([top_5_neighborhoods, bottom_5_neighborhoods])

plt.figure(figsize=(14, 8))
sns.barplot(x=neighborhood_plot_data.index, y=neighborhood_plot_data.values, palette='viridis')
plt.title('Top 5 and Bottom 5 Neighborhoods by Average Sale Price')
plt.xlabel('Neighborhood')
plt.ylabel('Average Sale Price ($)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Calculate the correlation between Year Built and Sale Price
correlation = df['YEAR BUILT'].corr(df['SALE PRICE'])
print(f"Correlation between Year Built and Sale Price: {correlation:.2f}")

# Visualize the relationship using a scatter plot with a regression line
plt.figure(figsize=(12, 7))
sns.regplot(x='YEAR BUILT', y='SALE PRICE', data=df, scatter_kws={'alpha':0.3, 's':10}, line_kws={'color':'red'})
plt.title('Sale Price vs. Year Built')
plt.xlabel('Year Built')
plt.ylabel('Sale Price ($)')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# Further investigate by grouping average sale price by year built (for specific years or bins)
# To make the trend clearer, let's look at average sale price in broad year built categories
def categorize_year_built(year):
    if year < 1900: return 'Pre-1900'
    elif year < 1940: return '1900-1939'
    elif year < 1980: return '1940-1979'
    else: return 'Post-1980'

df['YEAR_BUILT_CATEGORY'] = df['YEAR BUILT'].apply(categorize_year_built)

avg_price_by_year_category = df.groupby('YEAR_BUILT_CATEGORY')['SALE PRICE'].mean().reindex(['Pre-1900', '1900-1939', '1940-1979', 'Post-1980'])

print("\nAverage Sale Price by Year Built Category:")
print(avg_price_by_year_category.apply(lambda x: f'${x:,.2f}'))

plt.figure(figsize=(10, 6))
avg_price_by_year_category.plot(kind='bar', color='skyblue')
plt.title('Average Sale Price by Building Age Category')
plt.xlabel('Year Built Category')
plt.ylabel('Average Sale Price ($)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

display(df[['SALE PRICE', 'GROSS SQUARE FEET', 'PRICE_PER_SQFT']].head())

avg_price_by_building_type = df.groupby('BUILDING CLASS CATEGORY')['SALE PRICE'].mean().sort_values(ascending=False)

print("Average Sale Price by Building Class Category (Residential Only):")
print(avg_price_by_building_type.apply(lambda x: f'${x:,.2f}'))

plt.figure(figsize=(12, 7))
sns.barplot(x=avg_price_by_building_type.index, y=avg_price_by_building_type.values, palette='coolwarm')
plt.title('Average Sale Price by Residential Building Class Category')
plt.xlabel('Building Class Category')
plt.ylabel('Average Sale Price ($)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""**SQL REQUIREMENTS**"""

# Mapping Borough numbers to County Names
borough_to_county = {
    1: 'New York County (Manhattan)',
    2: 'Bronx County',
    3: 'Kings County (Brooklyn)',
    4: 'Queens County',
    5: 'Richmond County (Staten Island)'
}

df['COUNTY_NAME'] = df['BOROUGH'].map(borough_to_county)

print("Added 'COUNTY_NAME' column to the DataFrame. First 5 rows:")
print(df[['BOROUGH', 'COUNTY_NAME', 'SALE PRICE']].head())

# Calculate average and median sale price by county
avg_median_price_by_county = df.groupby('COUNTY_NAME')['SALE PRICE'].agg(['mean', 'median']).sort_values(by='mean', ascending=False)

print("\nAverage and Median Sale Price by County:")
print(avg_median_price_by_county)

# Display the results for clarity
print(f"\nFrom the analysis, we can see that {avg_median_price_by_county.index[0]} has the highest average sale price of ${avg_median_price_by_county.iloc[0]['mean']:,.2f},")
print(f"with a median sale price of ${avg_median_price_by_county.iloc[0]['median']:,.2f}.")
print(f"In contrast, {avg_median_price_by_county.index[-1]} has the lowest average sale price of ${avg_median_price_by_county.iloc[-1]['mean']:,.2f},")
print(f"with a median sale price of ${avg_median_price_by_county.iloc[-1]['median']:,.2f}.")

df['SALE_YEAR'] = df['SALE DATE'].dt.year

avg_sale_price_by_year = df.groupby('SALE_YEAR')['SALE PRICE'].mean()

plt.figure(figsize=(10, 6))
avg_sale_price_by_year.plot(kind='line', marker='o')
plt.title('Average Sale Price Over Time (by Year)')
plt.xlabel('Year')
plt.ylabel('Average Sale Price ($)')
plt.grid(True)
plt.xticks(avg_sale_price_by_year.index)
plt.tight_layout()
plt.show()

print("Average Sale Price by Year:")
print(avg_sale_price_by_year)

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure 'SALE DATE' is in datetime format
df['SALE DATE'] = pd.to_datetime(df['SALE DATE'])

# Extract year and month number
df['SALE_YEAR'] = df['SALE DATE'].dt.year
df['SALE_MONTH_NUM'] = df['SALE DATE'].dt.month

# Calculate average sale price by year and month
avg_price_by_year_month = df.groupby(['SALE_YEAR', 'SALE_MONTH_NUM'])['SALE PRICE'].mean().unstack(level=0)

# Plotting the average sale price over time by month for each year
plt.figure(figsize=(14, 7))
avg_price_by_year_month.plot(kind='line', marker='o', ax=plt.gca())
plt.title('Average Sale Price Trend by Month for Each Year')
plt.xlabel('Month')
plt.ylabel('Average Sale Price ($)')
plt.grid(True)
plt.xticks(range(1, 13), ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
plt.legend(title='Year')
plt.tight_layout()
plt.show()

print("Average Sale Price by Year and Month:")
print(avg_price_by_year_month)

top_10_neighborhoods = avg_price_by_neighborhood.head(10)

print("Top 10 Most Expensive Neighborhoods by Average Sale Price:")
print(top_10_neighborhoods.apply(lambda x: f'${x:,.2f}'))

plt.figure(figsize=(14, 8))
sns.barplot(x=top_10_neighborhoods.index, y=top_10_neighborhoods.values, palette='viridis')
plt.title('Top 10 Most Expensive Neighborhoods by Average Sale Price')
plt.xlabel('Neighborhood')
plt.ylabel('Average Sale Price ($)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

avg_price_by_borough_year = df.groupby(['BOROUGH', 'SALE_YEAR'])['SALE PRICE'].mean().reset_index()

# Calculate the previous year's average sale price within each borough group
avg_price_by_borough_year['PREV_YEAR_SALE_PRICE'] = avg_price_by_borough_year.groupby('BOROUGH')['SALE PRICE'].shift(1)

# Calculate the year-over-year percentage change
avg_price_by_borough_year['YOY_PERCENT_CHANGE'] = ((avg_price_by_borough_year['SALE PRICE'] - avg_price_by_borough_year['PREV_YEAR_SALE_PRICE']) / avg_price_by_borough_year['PREV_YEAR_SALE_PRICE']) * 100

print("Year-over-Year Percentage Change in Average Sale Price by Borough:")
print(avg_price_by_borough_year)

# Filter for 2017 to see the actual YOY change values
yoy_change_2017 = avg_price_by_borough_year[avg_price_by_borough_year['SALE_YEAR'] == 2017]
print("\nYear-over-Year Percentage Change (2016 to 2017) by Borough:")
# Updated to use .map for string formatting to avoid FutureWarning
print(yoy_change_2017.dropna(subset=['YOY_PERCENT_CHANGE']).set_index('BOROUGH')[['YOY_PERCENT_CHANGE']].map(lambda x: f'{x:.2f}%'))

avg_price_by_borough_month = df.groupby(['BOROUGH', 'SALE_MONTH_YEAR'])['SALE PRICE'].mean().reset_index()

# Sort by borough and month to ensure correct shifting
avg_price_by_borough_month = avg_price_by_borough_month.sort_values(by=['BOROUGH', 'SALE_MONTH_YEAR'])

# Calculate the previous month's average sale price within each borough group
avg_price_by_borough_month['PREV_MONTH_SALE_PRICE'] = avg_price_by_borough_month.groupby('BOROUGH')['SALE PRICE'].shift(1)

# Calculate the month-over-month percentage change
avg_price_by_borough_month['MOM_PERCENT_CHANGE'] = ((avg_price_by_borough_month['SALE PRICE'] - avg_price_by_borough_month['PREV_MONTH_SALE_PRICE']) / avg_price_by_borough_month['PREV_MONTH_SALE_PRICE']) * 100

print("Month-over-Month Percentage Change in Average Sale Price by Borough:")
print(avg_price_by_borough_month.dropna(subset=['MOM_PERCENT_CHANGE']).set_index(['BOROUGH', 'SALE_MONTH_YEAR']))

# Convert SALE_MONTH_YEAR to datetime for plotting
avg_price_by_borough_month['SALE_MONTH_YEAR_DT'] = avg_price_by_borough_month['SALE_MONTH_YEAR'].dt.to_timestamp()

# Visualize the Month-over-Month percentage change for each borough
plt.figure(figsize=(15, 8))
sns.lineplot(data=avg_price_by_borough_month, x='SALE_MONTH_YEAR_DT', y='MOM_PERCENT_CHANGE', hue='BOROUGH', marker='o')
plt.title('Month-over-Month Percentage Change in Average Sale Price by Borough')
plt.xlabel('Month-Year')
plt.ylabel('MoM % Change')
plt.xticks(rotation=45, ha='right')
plt.grid(True)
plt.tight_layout()
plt.show()

# Define the conditions for the era bands
conditions = [
    df['YEAR BUILT'] < 1950,
    (df['YEAR BUILT'] >= 1950) & (df['YEAR BUILT'] <= 2000),
    df['YEAR BUILT'] > 2000
]

# Define the choices (era band labels)
choices = ['pre-1950', '1950–2000', 'post-2000']

# Create the new 'BUILDING_ERA' column using numpy.select
df['BUILDING_ERA'] = np.select(conditions, choices, default='Unknown')

print("Distribution of properties by Building Era:")
print(df['BUILDING_ERA'].value_counts())

print("\nFirst 5 rows with the new 'BUILDING_ERA' column:")
print(df[['YEAR BUILT', 'BUILDING_ERA']].head())

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate transaction volume by month
monthly_transaction_volume = df.groupby('SALE_MONTH_YEAR').size().reset_index(name='Transaction Volume')

# Convert SALE_MONTH_YEAR to datetime for plotting
monthly_transaction_volume['SALE_MONTH_YEAR_DT'] = monthly_transaction_volume['SALE_MONTH_YEAR'].dt.to_timestamp()

# Plotting the transaction volume over time by month
plt.figure(figsize=(14, 7))
sns.lineplot(data=monthly_transaction_volume, x='SALE_MONTH_YEAR_DT', y='Transaction Volume', marker='o')
plt.title('Monthly Property Transaction Volume (Sept 2016 - Aug 2017)')
plt.xlabel('Month-Year')
plt.ylabel('Number of Sales')
plt.grid(True)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print("Monthly Property Transaction Volume:")
print(monthly_transaction_volume.set_index('SALE_MONTH_YEAR'))

# Identify months with highest and lowest volume
highest_volume_month = monthly_transaction_volume.loc[monthly_transaction_volume['Transaction Volume'].idxmax()]
lowest_volume_month = monthly_transaction_volume.loc[monthly_transaction_volume['Transaction Volume'].idxmin()]

print(f"\nThe month with the highest transaction volume was {highest_volume_month['SALE_MONTH_YEAR']} with {highest_volume_month['Transaction Volume']} sales.")
print(f"The month with the lowest transaction volume was {lowest_volume_month['SALE_MONTH_YEAR']} with {lowest_volume_month['Transaction Volume']} sales.")

avg_price_by_borough = df.groupby('BOROUGH')['SALE PRICE'].mean().rename('BOROUGH_AVG_SALE_PRICE')
df = df.merge(avg_price_by_borough, on='BOROUGH', how='left')
df['LUXURY_THRESHOLD'] = 2 * df['BOROUGH_AVG_SALE_PRICE']
df['IS_LUXURY'] = df['SALE PRICE'] > df['LUXURY_THRESHOLD']

print(f"Number of luxury properties (more than 2x borough average): {df['IS_LUXURY'].sum()}")
print("\nFirst 5 rows with new 'IS_LUXURY' column:")
print(df[['BOROUGH', 'SALE PRICE', 'BOROUGH_AVG_SALE_PRICE', 'LUXURY_THRESHOLD', 'IS_LUXURY']].head())

luxury_properties = df[df['IS_LUXURY'] == True]
print(f"Displaying the first 20 luxury properties (out of {len(luxury_properties)} total luxury properties):")
display(luxury_properties[['BOROUGH', 'NEIGHBORHOOD', 'SALE PRICE', 'GROSS SQUARE FEET', 'PRICE_PER_SQFT', 'BUILDING CLASS CATEGORY']].head(20))

"""**DASHBOARD REQUIREMENT**"""

print("**Dashboard Key Performance Indicators (KPIs)**")
print("---------------------------------------------------")

# 1. Total Sales
total_sales = df.shape[0]
print(f"Total Sales: {total_sales:,}")

# 2. Average Sale Price
avg_sale_price = df['SALE PRICE'].mean()
print(f"Average Sale Price: ${avg_sale_price:,.2f}")

# 3. Average Price per Square Foot
avg_price_per_sqft = df['PRICE_PER_SQFT'].mean()
print(f"Average Price per Square Foot: ${avg_price_per_sqft:,.2f}")

# 4. Most Expensive Borough (by average sale price)
# Re-using previously calculated values or recalculating if not available in current state
# (assuming avg_price_by_borough from previous execution is available and accurate)
if 'avg_price_by_borough' in locals():
    most_expensive_borough = avg_price_by_borough.index[0]
    most_expensive_borough_price = avg_price_by_borough.iloc[0]
else:
    # Fallback if the variable is not found (though it should be in this notebook state)
    avg_price_by_borough = df.groupby('BOROUGH')['SALE PRICE'].mean().sort_values(ascending=False)
    most_expensive_borough = avg_price_by_borough.index[0]
    most_expensive_borough_price = avg_price_by_borough.iloc[0]

# Mapping Borough numbers to County Names for better readability
borough_to_county = {
    1: 'New York County (Manhattan)',
    2: 'Bronx County',
    3: 'Kings County (Brooklyn)',
    4: 'Queens County',
    5: 'Richmond County (Staten Island)'
}
most_expensive_borough_name = borough_to_county.get(most_expensive_borough, f'Borough {most_expensive_borough}')

print(f"Most Expensive Borough (by avg sale price): {most_expensive_borough_name} (Avg: ${most_expensive_borough_price:,.2f})")

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming avg_price_by_borough is already calculated and available from previous steps
# If not, uncomment the following line:
# avg_price_by_borough = df.groupby('BOROUGH')['SALE PRICE'].mean().sort_values(ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x=avg_price_by_borough.index, y=avg_price_by_borough.values, palette='viridis')
plt.title('Average Sale Price by Borough')
plt.xlabel('Borough')
plt.ylabel('Average Sale Price ($)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""Price trend over time — line chart by year"""

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming avg_sale_price_by_year is already calculated and available
# If not, it can be recalculated as:
# df['SALE_YEAR'] = df['SALE DATE'].dt.year
# avg_sale_price_by_year = df.groupby('SALE_YEAR')['SALE PRICE'].mean()

plt.figure(figsize=(10, 6))
avg_sale_price_by_year.plot(kind='line', marker='o')
plt.title('Average Sale Price Over Time (by Year)')
plt.xlabel('Year')
plt.ylabel('Average Sale Price ($)')
plt.grid(True)
plt.xticks(avg_sale_price_by_year.index)
plt.tight_layout()
plt.show()

print("Average Sale Price by Year:")
print(avg_sale_price_by_year)

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate average sale price by day
avg_sale_price_by_day = df.groupby('SALE DATE')['SALE PRICE'].mean()

# Plotting the average sale price over time by day
plt.figure(figsize=(16, 8))
avg_sale_price_by_day.plot(kind='line', marker='o', linestyle='-', markersize=4)
plt.title('Average Sale Price Over Time (by Day)')
plt.xlabel('Date')
plt.ylabel('Average Sale Price ($)')
plt.grid(True)
plt.tight_layout()
plt.show()

print("Average Sale Price by Day (first 5 and last 5 entries):")
print(avg_sale_price_by_day.head())
print(avg_sale_price_by_day.tail())

"""Top 15 neighbourhoods by price — horizontal bar chart"""

import matplotlib.pyplot as plt
import seaborn as sns

# Get the top 15 neighborhoods by average sale price
top_15_neighborhoods = avg_price_by_neighborhood.head(15)

plt.figure(figsize=(14, 10))
sns.barplot(x=top_15_neighborhoods.values, y=top_15_neighborhoods.index, palette='magma')
plt.title('Top 15 Neighborhoods by Average Sale Price')
plt.xlabel('Average Sale Price ($)')
plt.ylabel('Neighborhood')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print("Top 15 Most Expensive Neighborhoods by Average Sale Price:")
print(top_15_neighborhoods.apply(lambda x: f'${x:,.2f}'))

"""Price per sqft heatmap by borough — if available, use a map visual"""

import matplotlib.pyplot as plt
import seaborn as sns

# Mapping Borough numbers to County Names for better readability
borough_to_county = {
    1: 'Manhattan',
    2: 'Bronx',
    3: 'Brooklyn',
    4: 'Queens',
    5: 'Staten Island'
}

# Assuming avg_price_sqft_by_borough is already calculated and available
# If not, it can be recalculated as:
# df['PRICE_PER_SQFT'] = df['SALE PRICE'] / df['GROSS SQUARE FEET']
# avg_price_sqft_by_borough = df.groupby('BOROUGH')['PRICE_PER_SQFT'].mean().sort_values(ascending=False)

# Apply the mapping to the index for plotting
plot_data = avg_price_sqft_by_borough.rename(index=borough_to_county)

plt.figure(figsize=(10, 6))
sns.barplot(x=plot_data.index, y=plot_data.values, palette='plasma')
plt.title('Average Price Per Square Foot by Borough')
plt.xlabel('Borough')
plt.ylabel('Average Price Per Square Foot ($)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print("Average Price Per Square Foot by Borough (with names):")
print(plot_data.apply(lambda x: f'${x:,.2f}'))

"""Building type vs avg price — bar chart"""



"""Transaction volume by month — bar chart showing seasonal pattern"""

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure monthly_transaction_volume is available (re-calculate if needed)
# monthly_transaction_volume = df.groupby('SALE_MONTH_YEAR').size().reset_index(name='Transaction Volume')
# monthly_transaction_volume['SALE_MONTH_YEAR_DT'] = monthly_transaction_volume['SALE_MONTH_YEAR'].dt.to_timestamp()

plt.figure(figsize=(14, 7))
sns.barplot(x='SALE_MONTH_YEAR_DT', y='Transaction Volume', data=monthly_transaction_volume, palette='viridis')
plt.title('Monthly Property Transaction Volume (Seasonal Pattern)')
plt.xlabel('Month-Year')
plt.ylabel('Number of Sales')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print("Monthly Property Transaction Volume:")
print(monthly_transaction_volume.set_index('SALE_MONTH_YEAR'))

"""**CROWN METRIC**"""

# Identify the borough with the strongest year-over-year price growth
yoy_change_2017_filtered = avg_price_by_borough_year[avg_price_by_borough_year['SALE_YEAR'] == 2017].dropna(subset=['YOY_PERCENT_CHANGE'])

if not yoy_change_2017_filtered.empty:
    strongest_growth_borough = yoy_change_2017_filtered.loc[yoy_change_2017_filtered['YOY_PERCENT_CHANGE'].idxmax()]
    print(f"\nThe borough with the strongest year-over-year price growth (2016-2017) is Borough {strongest_growth_borough['BOROUGH']} with a {strongest_growth_borough['YOY_PERCENT_CHANGE']:.2f}% increase.")
else:
    print("No year-over-year growth data available for 2017.")

# Addressing 'most consistently' with limited data
print("\nWith only two years of data (2016 and 2017), it's difficult to assess 'consistency' comprehensively. However, the borough with the strongest growth in this period (Borough 1 - Manhattan) showed the highest appreciation.")

# Time series chart showing average sale price for all boroughs on the same axis
plt.figure(figsize=(14, 8))
sns.lineplot(data=avg_price_by_borough_year, x='SALE_YEAR', y='SALE PRICE', hue='BOROUGH', marker='o')
plt.title('Average Sale Price Over Time by Borough (2016-2017)')
plt.xlabel('Year')
plt.ylabel('Average Sale Price ($)')
plt.xticks(avg_price_by_borough_year['SALE_YEAR'].unique())
plt.grid(True)
plt.legend(title='Borough')
plt.tight_layout()
plt.show()

print("\nAverage Sale Price by Borough and Year:")
print(avg_price_by_borough_year.pivot(index='SALE_YEAR', columns='BOROUGH', values='SALE PRICE'))

import matplotlib.pyplot as plt
import seaborn as sns

# Re-displaying the month-over-month calculation and plot from cell 0c6098aa
# This assumes df, avg_price_by_borough_month, and related columns are already defined

# Ensure 'SALE DATE' is in datetime format and 'SALE_MONTH_YEAR' is calculated
# (These steps were performed in cell de4eac06 and 0c6098aa)
# df['SALE DATE'] = pd.to_datetime(df['SALE DATE'])
# df['SALE_MONTH_YEAR'] = df['SALE DATE'].dt.to_period('M')

# Re-calculate avg_price_by_borough_month if necessary, or just use the existing one
# avg_price_by_borough_month = df.groupby(['BOROUGH', 'SALE_MONTH_YEAR'])['SALE PRICE'].mean().reset_index()
# avg_price_by_borough_month = avg_price_by_borough_month.sort_values(by=['BOROUGH', 'SALE_MONTH_YEAR'])
# avg_price_by_borough_month['PREV_MONTH_SALE_PRICE'] = avg_price_by_borough_month.groupby('BOROUGH')['SALE PRICE'].shift(1)
# avg_price_by_borough_month['MOM_PERCENT_CHANGE'] = ((avg_price_by_borough_month['SALE PRICE'] - avg_price_by_borough_month['PREV_MONTH_SALE_PRICE']) / avg_price_by_borough_month['PREV_MONTH_SALE_PRICE']) * 100

# Convert SALE_MONTH_YEAR to datetime for plotting (if not already done)
if 'SALE_MONTH_YEAR_DT' not in avg_price_by_borough_month.columns:
    avg_price_by_borough_month['SALE_MONTH_YEAR_DT'] = avg_price_by_borough_month['SALE_MONTH_YEAR'].dt.to_timestamp()

print("Month-over-Month Percentage Change in Average Sale Price by Borough:")
print(avg_price_by_borough_month.dropna(subset=['MOM_PERCENT_CHANGE']).set_index(['BOROUGH', 'SALE_MONTH_YEAR']))

# Visualize the Month-over-Month percentage change for each borough
plt.figure(figsize=(15, 8))
sns.lineplot(data=avg_price_by_borough_month, x='SALE_MONTH_YEAR_DT', y='MOM_PERCENT_CHANGE', hue='BOROUGH', marker='o')
plt.title('Month-over-Month Percentage Change in Average Sale Price by Borough')
plt.xlabel('Month-Year')
plt.ylabel('MoM % Change')
plt.xticks(rotation=45, ha='right')
plt.grid(True)
plt.legend(title='Borough')
plt.tight_layout()
plt.show()



"""## Quarter-over-Quarter (QoQ) Price Growth Analysis"""

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure 'SALE DATE' is in datetime format
df['SALE DATE'] = pd.to_datetime(df['SALE DATE'])

# Extract year and quarter to create a quarterly period
df['SALE_QUARTER'] = df['SALE DATE'].dt.to_period('Q')

# Calculate average sale price by borough and quarter
avg_price_by_borough_quarter = df.groupby(['BOROUGH', 'SALE_QUARTER'])['SALE PRICE'].mean().reset_index()

# Sort by borough and quarter to ensure correct shifting
avg_price_by_borough_quarter = avg_price_by_borough_quarter.sort_values(by=['BOROUGH', 'SALE_QUARTER'])

# Calculate the previous quarter's average sale price within each borough group
avg_price_by_borough_quarter['PREV_QUARTER_SALE_PRICE'] = avg_price_by_borough_quarter.groupby('BOROUGH')['SALE PRICE'].shift(1)

# Calculate the Quarter-over-Quarter percentage change
avg_price_by_borough_quarter['QOQ_PERCENT_CHANGE'] = ((avg_price_by_borough_quarter['SALE PRICE'] - avg_price_by_borough_quarter['PREV_QUARTER_SALE_PRICE']) / avg_price_by_borough_quarter['PREV_QUARTER_SALE_PRICE']) * 100

print("Quarter-over-Quarter Percentage Change in Average Sale Price by Borough:")
print(avg_price_by_borough_quarter.dropna(subset=['QOQ_PERCENT_CHANGE']).set_index(['BOROUGH', 'SALE_QUARTER']))

# Convert SALE_QUARTER to datetime for plotting
avg_price_by_borough_quarter['SALE_QUARTER_DT'] = avg_price_by_borough_quarter['SALE_QUARTER'].dt.to_timestamp()

# Visualize the Quarter-over-Quarter percentage change for each borough
plt.figure(figsize=(15, 8))
sns.lineplot(data=avg_price_by_borough_quarter, x='SALE_QUARTER_DT', y='QOQ_PERCENT_CHANGE', hue='BOROUGH', marker='o')
plt.title('Quarter-over-Quarter Percentage Change in Average Sale Price by Borough')
plt.xlabel('Quarter-Year')
plt.ylabel('QoQ % Change')
plt.xticks(rotation=45, ha='right')
plt.grid(True)
plt.legend(title='Borough')
plt.tight_layout()
plt.show()

"""### Identifying Most Consistent Appreciation

To determine 'most consistent' appreciation, we look for boroughs with relatively stable, positive QoQ growth and fewer drastic fluctuations. Given the limited data range (2016 Q3 to 2017 Q3), a robust assessment of 'consistency' is challenging, but we can observe trends.

From the chart above and the calculated QoQ changes, we can look for:

*   **Positive Growth:** Boroughs that consistently show positive QoQ percentage changes.
*   **Smaller Fluctuations:** Boroughs where the QoQ changes are not extremely volatile.

Looking at the `QOQ_PERCENT_CHANGE` values and the plot, we can analyze the growth patterns:

"""

# Calculate the standard deviation of QoQ changes to quantify consistency (lower std dev indicates more consistency)
consistency_metrics = avg_price_by_borough_quarter.groupby('BOROUGH')['QOQ_PERCENT_CHANGE'].agg(['mean', 'std']).dropna()

print("Mean and Standard Deviation of QoQ Percentage Change by Borough:")
print(consistency_metrics.apply(lambda x: pd.Series([f'{x[0]:.2f}%', f'{x[1]:.2f}%'], index=['mean', 'std']), axis=1))

# Identify borough with highest mean positive growth and lowest standard deviation (if applicable)
if not consistency_metrics.empty:
    # Filter for positive mean growth if desired
    positive_growth_metrics = consistency_metrics[consistency_metrics['mean'] > 0]

    if not positive_growth_metrics.empty:
        # Sort by mean (descending) and then by std (ascending) to find 'consistently high growth'
        most_consistent_growth = positive_growth_metrics.sort_values(by=['mean', 'std'], ascending=[False, True]).iloc[0]
        most_consistent_borough_id = most_consistent_growth.name
        most_consistent_borough_mean = most_consistent_growth['mean']
        most_consistent_borough_std = most_consistent_growth['std']

        # Map borough ID to name
        borough_to_county_name = {
            1: 'New York County (Manhattan)',
            2: 'Bronx County',
            3: 'Kings County (Brooklyn)',
            4: 'Queens County',
            5: 'Richmond County (Staten Island)'
        }
        most_consistent_borough_name = borough_to_county_name.get(most_consistent_borough_id, f'Borough {most_consistent_borough_id}')

        print(f"\nThe borough with the most consistently high positive QoQ price growth appears to be {most_consistent_borough_name}, with an average QoQ growth of {most_consistent_borough_mean:.2f}% and a standard deviation of {most_consistent_borough_std:.2f}% (indicating relatively stable growth).")
    else:
        print("No boroughs showed a positive average QoQ growth over the period.")
else:
    print("Not enough data to calculate consistency metrics.")

df.head()

import pandas as pd

# Convert date
df['SALE DATE'] = pd.to_datetime(df['SALE DATE'])

# Filter Bronx and explicitly create a copy to avoid SettingWithCopyWarning
bronx_df = df[df['COUNTY_NAME'] == 'Bronx County'].copy() # Changed to 'Bronx County' as seen in kernel state

# Create Year + Quarter
bronx_df['year'] = bronx_df['SALE DATE'].dt.year
bronx_df['quarter'] = bronx_df['SALE DATE'].dt.quarter

# Aggregate average price per quarter
quarterly = bronx_df.groupby(['year', 'quarter'])['SALE PRICE'].mean().reset_index()

# Calculate QoQ growth
quarterly['qoq_growth_pct'] = quarterly['SALE PRICE'].pct_change() * 100

# Calculate metrics
avg_growth = quarterly['qoq_growth_pct'].mean()
volatility = quarterly['qoq_growth_pct'].std()

print("Average QoQ Growth:", avg_growth)
print(f"Volatility (Std Dev): {volatility}") # Corrected print statement

# Ensure 'SALE DATE' is in datetime format and 'SALE_QUARTER' is extracted
df['SALE DATE'] = pd.to_datetime(df['SALE DATE'])
df['SALE_QUARTER'] = df['SALE DATE'].dt.to_period('Q')

# Calculate average sale price by neighborhood and quarter
avg_price_by_neighborhood_quarter = df.groupby(['NEIGHBORHOOD', 'SALE_QUARTER'])['SALE PRICE'].mean().reset_index()

# Sort by neighborhood and quarter to ensure correct shifting
avg_price_by_neighborhood_quarter = avg_price_by_neighborhood_quarter.sort_values(by=['NEIGHBORHOOD', 'SALE_QUARTER'])

# Calculate the previous quarter's average sale price within each neighborhood group
avg_price_by_neighborhood_quarter['PREV_QUARTER_SALE_PRICE'] = avg_price_by_neighborhood_quarter.groupby('NEIGHBORHOOD')['SALE PRICE'].shift(1)

# Calculate the Quarter-over-Quarter percentage change
avg_price_by_neighborhood_quarter['QOQ_PERCENT_CHANGE'] = ((avg_price_by_neighborhood_quarter['SALE PRICE'] - avg_price_by_neighborhood_quarter['PREV_QUARTER_SALE_PRICE']) / avg_price_by_neighborhood_quarter['PREV_QUARTER_SALE_PRICE']) * 100

# Calculate the mean and standard deviation of QoQ changes for each neighborhood
neighborhood_consistency_metrics = avg_price_by_neighborhood_quarter.groupby('NEIGHBORHOOD')['QOQ_PERCENT_CHANGE'].agg(['mean', 'std']).dropna()

print("Mean and Standard Deviation of QoQ Percentage Change by Neighborhood:")
# Display top and bottom of the metrics for inspection
print(neighborhood_consistency_metrics.apply(lambda x: pd.Series([f'{x[0]:.2f}%', f'{x[1]:.2f}%'], index=['mean', 'std']), axis=1).head())
print("...")
print(neighborhood_consistency_metrics.apply(lambda x: pd.Series([f'{x[0]:.2f}%', f'{x[1]:.2f}%'], index=['mean', 'std']), axis=1).tail())

# Identify neighborhood with most consistent growth and low volatility
if not neighborhood_consistency_metrics.empty:
    # Filter for positive mean growth
    positive_growth_neighborhoods = neighborhood_consistency_metrics[neighborhood_consistency_metrics['mean'] > 0]

    if not positive_growth_neighborhoods.empty:
        # Sort by standard deviation (ascending) first to prioritize low volatility,
        # then by mean (descending) to get higher growth among low volatility options.
        most_consistent_growth_neighborhood = positive_growth_neighborhoods.sort_values(by=['std', 'mean'], ascending=[True, False]).iloc[0]
        most_consistent_neighborhood_name = most_consistent_growth_neighborhood.name
        most_consistent_neighborhood_mean = most_consistent_growth_neighborhood['mean']
        most_consistent_neighborhood_std = most_consistent_growth_neighborhood['std']

        print(f"\nThe neighborhood with the most consistently high positive QoQ price growth and low volatility is {most_consistent_neighborhood_name}, with an average QoQ growth of {most_consistent_neighborhood_mean:.2f}% and a standard deviation of {most_consistent_neighborhood_std:.2f}%.")
    else:
        print("No neighborhoods showed a positive average QoQ growth over the period with enough data for consistency analysis.")
else:
    print("Not enough data to calculate consistency metrics for neighborhoods.")